export const DUMMY_THREAT_DATA = [
  {
    id: 10,
    actionItem: {
      id: 6,
      actionItemDetails:
        'In the process, address data sensitivity, data owner, handling of data, data retention limits, and disposal requirements, based on sensitivity and retention standards for the enterprise. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',
      actionItemSummary: 'Establish and maintain a data management process.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Data Protection',
      controlMapping:
        'CIS Control v8.0: (3.1), NIST CSF: PR.IP-6 (superset), ISO/IEC 27001:2013:',
      goodChoices: [Array],
      questionTitle: 'Do you have a Data Management Process?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.522Z',
      updated_at: '2021-12-13T07:46:12.522Z',
    },
    user: 29,
    state: 'resolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping:
      'CIS Control v8.0: (3.1), NIST CSF: PR.IP-6 (superset), ISO/IEC 27001:2013:',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.463Z',
    updated_at: '2022-01-05T02:54:39.478Z',
  },
  {
    id: 2,
    actionItem: {
      id: 46,
      actionItemDetails:
        'Train workforce members to recognize social engineering attacks, such as phishing, pre-texting, and tailgating.',
      actionItemSummary:
        'Train workforce members to recognize social engineering attacks.',
      category: 'People',
      questionReferenceID: [Array],
      securityDomain: 'Security Awareness and Skills Training',
      controlMapping: '',
      goodChoices: [Array],
      questionTitle:
        'Do you Train Workforce Members to Recognize Social Engineering Attacks?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.758Z',
      updated_at: '2021-12-13T07:46:12.758Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'People',
    controlMapping: '',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:53:36.345Z',
    updated_at: '2022-01-05T02:53:36.365Z',
  },
  {
    id: 4,
    actionItem: {
      id: 48,
      actionItemDetails:
        'Train workforce members on how to identify and properly store, transfer, archive, and destroy sensitive data. This also includes training workforce members on clear screen and desk best practices, such as locking their screen when they step away from their enterprise asset, erasing physical and virtual whiteboards at the end of meetings, and storing data and assets securely.',
      actionItemSummary:
        'Train workforce members on how to identify and properly store, transfer, archive, and destroy sensitive data. This also includes training workforce members on clear screen and desk best practices.',
      category: 'People',
      questionReferenceID: [Array],
      securityDomain: 'Security Awareness and Skills Training',
      controlMapping: '',
      goodChoices: [Array],
      questionTitle: 'Do you Train Workforce on Data Handling Best Practices?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.774Z',
      updated_at: '2021-12-13T07:46:12.774Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'People',
    controlMapping: '',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:53:36.345Z',
    updated_at: '2022-01-05T02:53:36.365Z',
  },
  {
    id: 5,
    actionItem: {
      id: 49,
      actionItemDetails:
        'Train workforce members to be aware of causes for unintentional data exposure. Example topics include mis-delivery of sensitive data, losing a portable end-user device, or publishing data to unintended audiences.',
      actionItemSummary:
        'Train workforce members to be aware of causes for unintentional data exposure.',
      category: 'People',
      questionReferenceID: [Array],
      securityDomain: 'Security Awareness and Skills Training',
      controlMapping: '',
      goodChoices: [Array],
      questionTitle:
        'Do you Train Workforce Members on Causes of Unintentional Data Exposure?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.784Z',
      updated_at: '2021-12-13T07:46:12.784Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'People',
    controlMapping: '',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:53:36.345Z',
    updated_at: '2022-01-05T02:53:36.364Z',
  },
  {
    id: 21,
    actionItem: {
      id: 24,
      actionItemDetails:
        'Establish and follow a process, preferably automated, for revoking access to enterprise assets, through disabling accounts immediately upon termination, rights revocation, or role change of a user. Disabling accounts, instead of deleting accounts, may be necessary to preserve audit trails.',
      actionItemSummary:
        'Establish and follow a process, preferably automated, for revoking access to enterprise assets.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Access Control Management',
      controlMapping:
        'CIS Control v8.0: (6.1, 6.2), NIST CSF: PR.AC-1 (subset), PR.IP-11 (subset), ISO/IEC 27001:2013: N/A',
      goodChoices: [Array],
      questionTitle: 'Do you Establish an Access Revoking Process?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.634Z',
      updated_at: '2021-12-13T07:46:12.634Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping:
      'CIS Control v8.0: (6.1, 6.2), NIST CSF: PR.AC-1 (subset), PR.IP-11 (subset), ISO/IEC 27001:2013: N/A',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.526Z',
    updated_at: '2022-01-05T02:54:39.545Z',
  },
  {
    id: 23,
    actionItem: {
      id: 26,
      actionItemDetails: 'Require MFA for remote network access.',
      actionItemSummary: 'Require MFA for remote network access.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Access Control Management',
      controlMapping:
        'CIS Control v8.0: (), NIST CSF: , ISO/IEC 27001:2013: N/A',
      goodChoices: [Array],
      questionTitle: 'Do you Require MFA for Remote Network Access?',
      priority: 'high',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.651Z',
      updated_at: '2021-12-13T07:46:12.651Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping: 'CIS Control v8.0: (), NIST CSF: , ISO/IEC 27001:2013: N/A',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.527Z',
    updated_at: '2022-01-05T02:54:39.545Z',
  },
  {
    id: 22,
    actionItem: {
      id: 25,
      actionItemDetails:
        'Require all externally-exposed enterprise or third-party applications to enforce MFA, where supported. Enforcing MFA through a directory service or SSO provider is a satisfactory implementation of this Safeguard.',
      actionItemSummary:
        'Require all externally-exposed enterprise or third-party applications to enforce MFA, where supported.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Access Control Management',
      controlMapping:
        'CIS Control v8.0: (), NIST CSF: , ISO/IEC 27001:2013: N/A',
      goodChoices: [Array],
      questionTitle: 'Do you Require MFA for Externally-Exposed Applications?',
      priority: 'high',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.645Z',
      updated_at: '2021-12-13T07:46:12.645Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping: 'CIS Control v8.0: (), NIST CSF: , ISO/IEC 27001:2013: N/A',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.526Z',
    updated_at: '2022-01-05T02:54:39.545Z',
  },
  {
    id: 20,
    actionItem: {
      id: 23,
      actionItemDetails:
        'Establish and follow a process, preferably automated, for granting access to enterprise assets upon new hire, rights grant, or role change of a user.',
      actionItemSummary:
        'Establish and follow a process, preferably automated, for granting access to enterprise assets upon new hire, rights grant, or role change of a user.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Access Control Management',
      controlMapping:
        'CIS Control v8.0: (6.1, 6.2), NIST CSF: PR.AC-1 (subset), PR.IP-11 (subset), ISO/IEC 27001:2013: N/A',
      goodChoices: [Array],
      questionTitle: 'Do you Establish an Access Granting Process?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.625Z',
      updated_at: '2021-12-13T07:46:12.625Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping:
      'CIS Control v8.0: (6.1, 6.2), NIST CSF: PR.AC-1 (subset), PR.IP-11 (subset), ISO/IEC 27001:2013: N/A',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.526Z',
    updated_at: '2022-01-05T02:54:39.545Z',
  },
  {
    id: 25,
    actionItem: {
      id: 28,
      actionItemDetails:
        '1. Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard. Automated scanning tools are preferred but manual monitoring of vulnerabilities in the wild against what is know to be in the enterprise is a less efficient option. It is here that we may see the importance of Control 1.1 and 2.1. <br/>2. Establish a remediation process for any identified vulnerabilities.This should identify priorities for remediation based on enterprise risk. This process should have monthly or more frequent reviews.',
      actionItemSummary:
        'Establish and maintain a documented vulnerability management process for enterprise assets and Establish a remediation process for any identified vulnerabilities.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Continuous Vulnerability Management',
      controlMapping:
        'CIS Control v8.0: (7.1), NIST CSF: ID.RA-1 (subset), ISO/IEC 27001:2013: N/A',
      goodChoices: [Array],
      questionTitle: 'Do you have a vulnerability management process?',
      priority: 'high',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.667Z',
      updated_at: '2021-12-13T07:46:12.667Z',
    },
    user: 29,
    state: 'resolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping:
      'CIS Control v8.0: (7.1), NIST CSF: ID.RA-1 (subset), ISO/IEC 27001:2013: N/A',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.527Z',
    updated_at: '2022-01-05T02:54:39.546Z',
  },
  {
    id: 32,
    actionItem: {
      id: 35,
      actionItemDetails:
        'Ensure only fully supported browsers and email clients are allowed to execute in the enterprise, only using the latest version of browsers and email clients provided through the vendor.',
      actionItemSummary:
        'Ensure only fully supported browsers and email clients are allowed to execute in the enterprise, only using the latest version of browsers and email clients provided through the vendor.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Email and Web Browser Protections',
      controlMapping:
        'CIS Control v8.0: (9.1), NIST CSF: PR.IP-1 (subset), ISO/IEC 27001:2013: A.8.1.3 (subset)',
      goodChoices: [Array],
      questionTitle:
        'Do you use only fully supported browsers and Email clients?',
      priority: 'high',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.702Z',
      updated_at: '2021-12-13T07:46:12.702Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping:
      'CIS Control v8.0: (9.1), NIST CSF: PR.IP-1 (subset), ISO/IEC 27001:2013: A.8.1.3 (subset)',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.592Z',
    updated_at: '2022-01-05T02:54:39.610Z',
  },
  {
    id: 7,
    actionItem: {
      id: 51,
      actionItemDetails:
        'Train workforce to understand how to verify and report out-of-date software patches or any failures in automated processes and tools. Part of this training should include notifying IT personnel of any failures in automated processes and tools.',
      actionItemSummary:
        'Train workforce to understand how to verify and report out-of-date software patches or any failures in automated processes and tools.',
      category: 'People',
      questionReferenceID: [Array],
      securityDomain: 'Security Awareness and Skills Training',
      controlMapping: '',
      goodChoices: [Array],
      questionTitle:
        'Do you Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates?',
      priority: 'medium',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.784Z',
      updated_at: '2021-12-13T07:46:12.784Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'People',
    controlMapping: '',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:53:36.349Z',
    updated_at: '2022-01-05T02:53:36.361Z',
  },
  {
    id: 36,
    actionItem: {
      id: 42,
      actionItemDetails:
        'Protect recovery data with equivalent controls to the original data. Reference encryption or data separation, based on requirements.',
      actionItemSummary:
        'Protect recovery data with equivalent controls to the original data. Reference encryption or data separation, based on requirements.',
      category: 'Process',
      questionReferenceID: [Array],
      securityDomain: 'Data Recovery',
      controlMapping:
        'CIS Control v8.0: (11.3), NIST CSF: , ISO/IEC 27001:2013: N/A',
      goodChoices: [Array],
      questionTitle: 'Do you Protect Recovery Data?',
      priority: 'high',
      created_by: null,
      updated_by: null,
      created_at: '2021-12-13T07:46:12.736Z',
      updated_at: '2021-12-13T07:46:12.736Z',
    },
    user: 29,
    state: 'unresolved',
    customActionItem: null,
    type: 'actionItem',
    company: 1,
    category: 'Process',
    controlMapping:
      'CIS Control v8.0: (11.3), NIST CSF: , ISO/IEC 27001:2013: N/A',
    created_by: null,
    updated_by: null,
    created_at: '2022-01-05T02:54:39.595Z',
    updated_at: '2022-01-05T02:54:39.610Z',
  },
]
