image: node:16.14.0
clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly
options:
  docker: true
  size: 2x
definitions:
  caches:
    sonar: ~/.sonar/cache
    npm: $HOME/.npm
  services:
    docker:
      memory: 4096
    sonar-service:
      type: docker
      memory: 4096
    build-service:
      image: node
      memory: 2048

pipelines:
  pull-requests:
    '**':
      - step:
          name: Sonar Check
          caches:
            - node
          script:
            - pipe: sonarsource/sonarcloud-scan:1.4.0
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
                EXTRA_ARGS: '-Dsonar.sources=. -Dsonar.tests=. -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
          services:
            - sonar-service
          size: 2x
      - step:
          name: Merge Checks
          caches:
            - node
          script:
            - yarn
            - yarn build
          services:
            - docker
          size: 2x

  branches:
    develop:
      - step:
          name: Continuum app develop deployment
          script:
              - apt-get update
              - apt-get install sshpass
              - sshpass -p $SSH_PASS_CONTINUUM ssh root@$SSH_HOST_CONTINUUM -o StrictHostKeyChecking=no sh /root/app/src/develop/docker/deploy.sh app $BITBUCKET_BRANCH develop-app
          services:
            - docker
          size: 2x

    release/*:
      - parallel:
        - step:
            name: Continuum app staging deployment
            script:
              - pipe: atlassian/ssh-run:0.3.1
                variables:
                  SSH_USER: 'root'
                  SERVER: '108.61.251.54'
                  MODE: 'command'
                  COMMAND: 'cd /root/app/src/staging/docker/ && ./deploy.sh app $BITBUCKET_BRANCH staging-app'
            services:
            - docker
            size: 2x
        - step:
            name: Scotpac app staging deployment
            script:
              - pipe: atlassian/ssh-run:0.3.1
                variables:
                  SSH_USER: 'root'
                  SERVER: '149.28.173.71'
                  MODE: 'command'
                  COMMAND: 'cd /root/app/src/continuum-staging/docker/ && ./deploy-nextjs.sh continuum-app $BITBUCKET_BRANCH'
            services:
            - docker
            size: 2x
        - step:
            name: Mackay app staging deployment
            script:
              - pipe: atlassian/ssh-run:0.3.1
                variables:
                  SSH_USER: 'root'
                  SERVER: '139.180.166.17'
                  MODE: 'command'
                  COMMAND: 'cd /root/app/src/staging/docker/ && ./deploy.sh app $BITBUCKET_BRANCH staging-app'
            services:
            - docker
            size: 2x

    continuum/*:
      - step:
          name: Continuum app production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '108.61.251.54'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/prod/docker/ && ./deploy.sh app $BITBUCKET_BRANCH prod-app'

    mackay/*:
      - step:
          name: Mackay app production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '139.180.166.17'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/prod/docker/ && ./deploy.sh app $BITBUCKET_BRANCH production-app'

    scotpac/*:
      - step:
          name: Scotpac app production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '149.28.173.71'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/continuum-production/docker/ && ./deploy-nextjs.sh continuum-app $BITBUCKET_BRANCH continuum-app-prod'
