image: node:14.17.6

pipelines:
  pull-requests:
    '**':
      - step:
          name: Merge Checks
          caches:
            - node
          script:
            - yarn
            - yarn build
  branches:

    release/*:
      - parallel:
        - step:
            name: Scotpac admin staging deployment
            script:
              - pipe: atlassian/ssh-run:0.3.1
                variables:
                  SSH_USER: 'root'
                  SERVER: '149.28.173.71'
                  MODE: 'command'
                  COMMAND: 'cd /root/app/src/continuum-staging/docker/ && ./deploy-nextjs.sh continuum-admin $BITBUCKET_BRANCH'

        - step:
            name: Continuum admin staging deployment
            script:
              - pipe: atlassian/ssh-run:0.3.1
                variables:
                  SSH_USER: 'root'
                  SERVER: '108.61.251.54'
                  MODE: 'command'
                  COMMAND: 'cd /root/app/src/staging/docker/ && ./deploy.sh admin $BITBUCKET_BRANCH staging-admin'

        - step:
            name: Mackay admin Staging deployment
            script:
              - pipe: atlassian/ssh-run:0.3.1
                variables:
                  SSH_USER: 'root'
                  SERVER: '139.180.166.17'
                  MODE: 'command'
                  COMMAND: 'cd /root/app/src/staging/docker/ && ./deploy.sh admin $BITBUCKET_BRANCH staging-admin'

    develop:
      - step:
          name: Continuum admin develop deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '108.61.251.54'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/develop/docker/ && ./deploy.sh admin $BITBUCKET_BRANCH develop-admin'

    continuum/*:
      - step:
          name: Continuum admin production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '108.61.251.54'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/prod/docker/ && ./deploy.sh admin $BITBUCKET_BRANCH prod-admin'                

    mackay/*:
      - step:
          name: Mackay admin production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '139.180.166.17'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/prod/docker/ && ./deploy.sh admin $BITBUCKET_BRANCH production-admin'

    scotpac/*:
      - step:
          name: Scotpac admin production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '149.28.173.71'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/continuum-production/docker/ && ./deploy-nextjs.sh continuum-admin $BITBUCKET_BRANCH continuum-admin-prod'
