image: node:14.17.6
clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly
options:
  docker: true
definitions:
  caches:
    sonar: ~/.sonar/cache
    npm: $HOME/.npm
  services:
    docker:
      memory: 2048
    sonar-service:
      type: docker
      memory: 2048
pipelines:
  pull-requests:
    '**':
      - step:
          name: Sonar Check
          caches:
            - node
          script:
            - pipe: sonarsource/sonarcloud-scan:1.4.0
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
                EXTRA_ARGS: '-Dsonar.sources=. -Dsonar.tests=. -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
          services:
            - sonar-service
          size: 2x
      - step:
          name: Merge Checks
          caches:
            - node
          script:
            - yarn
            - yarn build
  branches:
    release/*:
      - parallel:
          - step:
              name: Continuum api staging deployment
              script:
                - pipe: atlassian/ssh-run:0.3.1
                  variables:
                    SSH_USER: 'root'
                    SERVER: '149.28.173.71'
                    MODE: 'command'
                    COMMAND: 'cd /root/app/src/continuum-staging/docker/ && ./deploy-strapi.sh continuum-api $BITBUCKET_BRANCH'

          - step:
              name: Continuum api staging deployment
              script:
                - pipe: atlassian/ssh-run:0.3.1
                  variables:
                    SSH_USER: 'root'
                    SERVER: '108.61.251.54'
                    MODE: 'command'
                    COMMAND: 'cd /root/app/src/staging/docker/ && ./deploy.sh api $BITBUCKET_BRANCH staging-api'

          - step:
              name: Mackay api staging deployment
              script:
                - pipe: atlassian/ssh-run:0.3.1
                  variables:
                    SSH_USER: 'root'
                    SERVER: '139.180.166.17'
                    MODE: 'command'
                    COMMAND: 'cd /root/app/src/staging/docker/ && ./deploy.sh api $BITBUCKET_BRANCH staging-api'

    develop:
      - step:
          name: Continuum api develop deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '108.61.251.54'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/develop/docker/ && ./deploy.sh api $BITBUCKET_BRANCH develop-api'
    continuum/*:
      - step:
          name: Continuum api production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '108.61.251.54'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/prod/docker/ && ./deploy.sh api $BITBUCKET_BRANCH prod-api'

    mackay/*:
      - step:
          name: Mackay api production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '139.180.166.17'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/prod/docker/ && ./deploy.sh api $BITBUCKET_BRANCH production-api'

    scotpac/*:
      - step:
          name: Scotpac api production deployment
          script:
            - pipe: atlassian/ssh-run:0.3.1
              variables:
                SSH_USER: 'root'
                SERVER: '149.28.173.71'
                MODE: 'command'
                COMMAND: 'cd /root/app/src/continuum-production/docker/ && ./deploy-strapi.sh continuum-api $BITBUCKET_BRANCH continuum-api-prod'
